"""
Pytest configuration & shared fixtures for OCR service tests.

Strategy:
- Mock easyocr.Reader (avoid 100MB model download in CI)
- Disable TS backend callback in tests
- Provide sample image fixtures
- Provide FastAPI TestClient
"""
import io
import os
import pytest
from unittest.mock import patch, MagicMock, AsyncMock

# Disable callback to Backend TS in test environment
os.environ["SYNC_CALLBACK_ENABLED"] = "false"
os.environ["INTERNAL_AUTH_TOKEN"] = "test-token"
os.environ["TS_BACKEND_URL"] = "http://localhost:3000/api/v1/nota"


# ─────────────────────────────────────────────
# Sample image fixtures
# ─────────────────────────────────────────────

@pytest.fixture
def receipt_png_1x1() -> bytes:
    """Valid 200x200 PNG generated by Pillow (cv2-decodable)."""
    with open("tests_py/fixtures/receipt_valid.png", "rb") as f:
        return f.read()


@pytest.fixture
def receipt_jpeg_minimal() -> bytes:
    """Valid 200x200 JPEG generated by Pillow."""
    with open("tests_py/fixtures/receipt_valid.jpg", "rb") as f:
        return f.read()


@pytest.fixture
def receipt_webp() -> bytes:
    """Valid 200x200 WebP generated by Pillow."""
    with open("tests_py/fixtures/receipt_valid.webp", "rb") as f:
        return f.read()


@pytest.fixture
def not_image_text() -> bytes:
    """Plain text file (not an image)."""
    with open("tests_py/fixtures/not_image.txt", "rb") as f:
        return f.read()


@pytest.fixture
def large_image() -> bytes:
    """Image file larger than 15MB limit."""
    with open("tests_py/fixtures/large_16mb.png", "rb") as f:
        data = f.read()
    # Pad to > 15MB
    return data + b"\x00" * (16 * 1024 * 1024)


# ─────────────────────────────────────────────
# Mock easyocr to avoid model download
# ─────────────────────────────────────────────

@pytest.fixture
def mock_easyocr():
    """Mock easyocr.Reader.readtext to return fixed text."""
    with patch("app.ocr.reader") as mock_reader:
        mock_reader.readtext = MagicMock(
            return_value=[
                (None, "Nasi Goreng", None),
                (None, "RP 25.000", None),
                (None, "Total RP 55.000", None),
            ]
        )
        yield mock_reader


@pytest.fixture
def mock_easyocr_empty():
    """Mock easyocr to return empty results (no text found)."""
    with patch("app.ocr.reader") as mock_reader:
        mock_reader.readtext = MagicMock(return_value=[])
        yield mock_reader


# ─────────────────────────────────────────────
# Mock httpx callback to Backend TS
# ─────────────────────────────────────────────

@pytest.fixture
def mock_httpx_callback():
    """Mock httpx.AsyncClient.post for the sync callback."""
    with patch("httpx.AsyncClient") as mock_client:
        mock_instance = AsyncMock()
        mock_instance.post = AsyncMock(
            return_value=MagicMock(status_code=200, text="")
        )
        mock_client.return_value.__aenter__.return_value = mock_instance
        mock_client.return_value.__aexit__.return_value = None
        yield mock_instance


# ─────────────────────────────────────────────
# FastAPI TestClient
# ─────────────────────────────────────────────

@pytest.fixture
def client(mock_easyocr, mock_httpx_callback):
    """FastAPI TestClient with easyocr and httpx mocked."""
    from fastapi.testclient import TestClient
    from main import app
    with TestClient(app) as c:
        yield c


@pytest.fixture
def client_no_mock():
    """FastAPI TestClient without mocks (use sparingly)."""
    from fastapi.testclient import TestClient
    from main import app
    with TestClient(app) as c:
        yield c
